### ISSUE TITLE
Dependency for STAR

### ISSUE THREAD

**Issue by aksenia** [Magdoll/SQANTI2#1]
Hi Liz, 

I am unsure what is the python STAR module that you refer to in the line 44 of sqanti_qc2.py? Thanks!

**Comment by Magdoll** [comment]
my bad. That's supposed to be [STAR.py](https://github.com/Magdoll/cDNA_Cupcake/blob/master/sequence/STAR.py) that's in `cDNA_Cupcake/sequence` which I just pushed.

You'll add `cDNA_Cupcake/sequence` to $PYTHONPATH which will allow the `import STAR` to work.

--Liz

**Comment by aksenia** [comment]
Makes sense! Thanks.
