### ISSUE TITLE
mapping error in sqanti_qc2.py

### ISSUE THREAD

**Issue by nancyjf** [Magdoll/SQANTI2#13]
Hey Liz,
I'm running your latest version of sqanti2 (v2.6, and cupcake at v6.8) and I'm getting an error when the script calls gmap to align the isoforms (in bold below). It looks like the gmap arguments are out of order: the gmap directory is being passed to the gmap command as "--cross-species" instead of as the path I provided in the -x parameter. The script I ran was:

python <path>/SQANTI2/sqanti_qc2.py \
           --aligner_choice=gmap \
           --cage_peak <path>/hg38.cage_peak_phase1and2combined_coord.bed \
           --polyA_motif_list <path>/human_polyA_list.txt \
           -x <path>/GRCh38.p12 -t 24 -z \
           -o BS6.isoseq3_polished.hq.uniq.sorted.collapsed.filtered.rep -d <path>  \
           -c <path>/intropolis.v1.hg19_with_liftover_to_hg38.tsv \
           -fl <path>/BS6.isoseq3_polished.hq.uniq.sorted.collapsed.filtered.abundance.txt \
          <path>/BS6.isoseq3_polished.all.uniq.sorted.collapsed.filtered.rep.fa \
          <path>/gencode.v30.chr_patch_hapl_scaff.annotation.gtf \
          <path>/GRCh38.p12.genome.fa

Thanks in advance for checking this out!
Best,
Nancy

####################################################################
R scripting front-end version 3.3.1 (2016-06-21)
Cleaning up isoform IDs...
Cleaned up isoform fasta file written to: <path>/BS6.isoseq3_polished.hq.uniq.sorted.collapsed.filtered.rep.renamed.fasta

**GMAP version 2019-02-15 called with args: gmap.sse42 -D --cross-species -n 1 --max-intronlength-middle=2000000 --max-intronlength-ends=2000000 -L 3000000 -f samse -t 24 <gmap_path> -d GRCh38.p12 -z sense_force <path>/BS6.isoseq3_polished.hq.uniq.sorted.collapsed.filtered.rep.renamed.fasta
Note: -n 1 will not report chimeric alignments.  If you want a single alignment plus chimeras, use -n 0 instead.**

Checking compiler assumptions for SSE2: 6B8B4567 327B23C6 xor=59F066A1
Checking compiler assumptions for SSE4.1: -103 -58 max=198 => compiler zero extends
Checking compiler options for SSE4.2: 6B8B4567 __builtin_clz=1 __builtin_ctz=0 _mm_popcnt_u32=17 __builtin_popcount=17
Finished checking compiler assumptions
**Unable to find genome directory --cross-species**
Either recompile the GMAP package to have the correct default directory (seen by doing gmap --version),
or use the -D flag to gmap to specify the correct genome directory.

**Comment by Magdoll** [comment]
This is now fixed in v2.7.
