### ISSUE TITLE
Collapsed header in fasta file

### ISSUE THREAD

**Issue by tay45** [Magdoll/SQANTI2#14]
Hello Magdoll,

My collapsed header after Iso-Seq3 and minimap2 is slightly different to your example.  Is it ok to run SQANTI? Thank you!

>PB.1.1|chr1:184917-199875(-)|transcript/19866 transcript/19866 full_length_coverage=28;length=1754;num_subreads=60
>PB.2.1|chr1:827670-843589(+)|transcript/11029 transcript/11029 full_length_coverage=2;length=2604;num_subreads=54
>PB.3.1|chr1:944203-959277(-)|transcript/15184 transcript/15184 full_length_coverage=2;length=2218;num_subreads=22
.
.
.

**Comment by Magdoll** [comment]
Hi @xogur ,
I believe this will work. I will be adding sequence format checking to SQANTI2 soon.
-Liz

**Comment by tay45** [comment]
Thank you!
