### ISSUE TITLE
Intropolis for hg38 genome, modified into STAR junction format.

### ISSUE THREAD

**Issue by mdeloger** [Magdoll/SQANTI2#15]
Hi @Magdoll,

may will be possible to download somewhere a "SQANTI2 ready-to-use" file (in STAR junction format) corresponding to Intropolis for hg38 and hg19 genome ? Or at least include a script that permits to make the conversion in STAR junction format, please ?

In fact, it seems that none of the files downloadable in the Intropolis github are in the good format for SQANTI2, or maybe I am wrong ?

Thank you very much in advance for your answer

Best regards

**Comment by Magdoll** [comment]
Hi @mdeloger ,
Yes I actually put in the wrong link in the SQANTI2 README. The FANTOM5 Cage peak data, polyA list, and Intropolis reformatted BED files are here:
https://github.com/Magdoll/images_public/tree/master/SQANTI2_support_data

For Intropolis currently I only have hg38. I'll put in hg19 later.
--Liz
