### ISSUE TITLE
ERROR: unrecognized arguments: --is_fusion

### ISSUE THREAD

**Issue by tay45** [Magdoll/SQANTI2#17]
Hello Magdoll,

I have gotten an error related to the fusion transcript option (--is_fusion). I attached my log at below. Do I need to update the version? Please let me know how I can resolve this issue. Thank you!
-------------------------------------
R scripting front-end version 3.5.1 (2018-07-02)
usage: sqanti_qc2.py [-h] [--aligner_choice {minimap2,deSALT,gmap}]
                     [--cage_peak CAGE_PEAK]
                     [--polyA_motif_list POLYA_MOTIF_LIST]
                     [--phyloP_bed PHYLOP_BED] [--skipORF] [-g]
                     [-e EXPRESSION] [-x GMAP_INDEX] [-t GMAP_THREADS] [-z]
                     [-o OUTPUT] [-d DIR] [-c COVERAGE] [-s SITES] [-w WINDOW]
                     [--geneid] [-fl FL_COUNT] [-v]
                     isoforms annotation genome
sqanti_qc2.py: error: unrecognized arguments: --is_fusion /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/nalm6e/fusion/hq_isoforms.fasta.fusion.abundance.txt

**Comment by Magdoll** [comment]
@xogur ,
Yes you need the latest version.
-Liz
