### ISSUE TITLE
ERROR: --is_fusion 

### ISSUE THREAD

**Issue by tay45** [Magdoll/SQANTI2#18]
Hello Magdoll,

I have updated the latest version of the SQANTI2. But, I can't still use the '--is_fusion'. I have downloaded it from https://github.com/Magdoll/SQANTI2. Did I download the correct one? Thank you!

----------------------------------------

sqanti_qc2.py -t 30 ../collapse.collapsed.rep.fq ../gencode.v30.annotation.gtf ../GRCh38.p12.genome.fa --cage_peak ../hg38.cage_peak_phase1and2combined_coord.bed --coverage ../intropolis.v1.hg19_with_liftover_to_hg38.tsv.min_count_10.modified --fl_count ../abundance/collapse.collapsed.abundance.txt --is_fusion ../hq_isoforms.fasta.fusion.rep.fq

R scripting front-end version 3.5.1 (2018-07-02)
usage: sqanti_qc2.py [-h] [--aligner_choice {minimap2,deSALT,gmap}]
                     [--cage_peak CAGE_PEAK]
                     [--polyA_motif_list POLYA_MOTIF_LIST]
                     [--phyloP_bed PHYLOP_BED] [--skipORF] [--is_fusion] [-g]
                     [-e EXPRESSION] [-x GMAP_INDEX] [-t GMAP_THREADS] [-z]
                     [-o OUTPUT] [-d DIR] [-c COVERAGE] [-s SITES] [-w WINDOW]
                     [--geneid] [-fl FL_COUNT] [-v]
                     isoforms annotation genome
sqanti_qc2.py: error: unrecognized arguments: /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/nalm6e/fusion/hq_isoforms.fasta.fusion.rep.fq

**Comment by Magdoll** [comment]
Hi,
Two things:

1. `--fl_count` is currently unsupported. You can provide the option but it doesn't do anything just yet. I'm working on it.

2. `--is_fusion` should NOT be provided with an argument. That is where your error message came from.

Try running:

```
sqanti_qc2.py -t 30 ../collapse.collapsed.rep.fq ../gencode.v30.annotation.gtf ../GRCh38.p12.genome.fa --cage_peak ../hg38.cage_peak_phase1and2combined_coord.bed --coverage ../intropolis.v1.hg19_with_liftover_to_hg38.tsv.min_count_10.modified --is_fusion 
```
