### ISSUE TITLE
--is_fusion (subprocess.CalledProcessError:)

### ISSUE THREAD

**Issue by tay45** [Magdoll/SQANTI2#19]
Hello Magdoll,

I did run the sqanti_qc2.py according to your suggestion as below;

sqanti_qc2.py -t 30 ../hq_isoforms.fasta.fusion.rep.fq  ../gencode.v30.annotation.gtf ../GRCh38.p12.genome.fa --cage_peak ../hg38.cage_peak_phase1and2combined_coord.bed --coverage ../intropolis.v1.hg19_with_liftover_to_hg38.tsv.min_count_10.modified --is_fusion

I did replace the collapse fastq with the fusion fastq, which contained the PBfusion.x ids. But, I got an error as below. Could you please let me know what was wrong? Thank you for your help!

R scripting front-end version 3.5.1 (2018-07-02)
Cleaning up isoform IDs...
Cleaned up isoform fasta file written to: /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/nalm6e/fusion/hq_isoforms.fasta.fusion.rep.renamed.fasta
[M::mm_idx_gen::91.598*1.86] collected minimizers
[M::mm_idx_gen::123.672*2.81] sorted minimizers
[M::main::123.673*2.81] loaded/built the index for 593 target sequence(s)
[M::mm_mapopt_update::128.297*2.74] mid_occ = 803
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 593
[M::mm_idx_stat::130.498*2.71] distinct minimizers: 167309999 (34.26% are singletons); average occurrences: 6.324; average spacing: 3.074
[M::worker_pipeline::131.405*2.74] mapped 43 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -ax splice --secondary=no -C5 -ub -t 30 /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/GRCh38.p12.genome.fa /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/nalm6e/fusion/hq_isoforms.fasta.fusion.rep.renamed.fasta
[M::main] Real time: 131.678 sec; CPU: 360.729 sec; Peak RSS: 18.695 GB
output written to /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/nalm6e/squanti2-3/hq_isoforms.fasta.fusion.rep.renamed_corrected.fasta
error: , /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/nalm6e/squanti2-3/hq_isoforms.fasta.fusion.rep.renamed_corrected.fasta
**** Running SQANTI...
**** Parsing provided files....
Reading genome fasta /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/GRCh38.p12.genome.fa....
****Aligning reads with Minimap2...
**** Predicting ORF sequences...
Traceback (most recent call last):
  File "/opt/SQANTI2/20190618/bin/sqanti_qc2.py", line 1599, in <module>
    main()
  File "/opt/SQANTI2/20190618/bin/sqanti_qc2.py", line 1595, in main
    run(args)
  File "/opt/SQANTI2/20190618/bin/sqanti_qc2.py", line 1248, in run
    orfDict = correctionPlusORFpred(args, genome_dict)
  File "/opt/SQANTI2/20190618/bin/sqanti_qc2.py", line 480, in correctionPlusORFpred
    if subprocess.check_call(cmd, shell=True, cwd=gmst_dir)!=0:
  File "/opt/SQANTI2/20190618/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'perl /opt/SQANTI2/20190618/bin/utilities/gmst/gmst.pl -faa --strand direct --fnn --output /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/nalm6e/squanti2-3/GMST/GMST_tmp /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/nalm6e/squanti2-3/hq_isoforms.fasta.fusion.rep.renamed_corrected.fasta' returned non-zero exit status 1

**Comment by Magdoll** [comment]
Hi,
It looks like something went wrong in writing out the error correct fasta. 

Can you just share the input file `hq_isoforms.fasta.fusion.rep.fq` confidentially? I think it's going to be a lot faster than trying to troubleshoot in the dark here. If you can share, plz give me an email to request file upload.

--Liz

**Comment by tay45** [comment]
Hello,

I can share the file. How can I upload it?

Thank you,

Taehee

2019년 7월 16일 (화) 오후 12:59, Elizabeth Tseng <notifications@github.com>님이 작성:

**Comment by Magdoll** [comment]
I need an email.

**Comment by Magdoll** [comment]
Hi,
I have been able to run this on the latest SQANTI2 (v3.2) after minor fixes to the code base. Please try again.

The command i used was:


```
python sqanti_qc2.py -t 30 input.fq gencode.v29.annotation.gtf hg38.fa --is_fusion
```

--Liz

**Comment by tay45** [comment]
Hello,

Thank you very much! It is working.

Best,

Taehee

**Comment by navajeet123** [comment]
Dear Author,
can you please help to resolve this.
============================ERROR==================
Reading genome fasta 1.fasta.masked....
****Aligning reads with Minimap2...
Traceback (most recent call last):
  File "./sqanti_qc2.py", line 1794, in <module>
    main()
  File "./sqanti_qc2.py", line 1790, in main
    run(args)
  File "./sqanti_qc2.py", line 1415, in run
    orfDict = correctionPlusORFpred(args, genome_dict)
  File "./sqanti_qc2.py", line 481, in correctionPlusORFpred
    if subprocess.check_call(cmd, shell=True)!=0:
  File "/lib/python3.7/subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'gffread IsoSeq_v1.0.Squanti.renamed_corrected.gtf.tmp -T -o IsoSeq_v1.0.Squanti.renamed_corrected.gtf' returned non-zero exit status 127

Thanks
