### ISSUE TITLE
No gene names in the output result

### ISSUE THREAD

**Issue by Wenwen420** [Magdoll/SQANTI2#21]
Hi @Magdoll
    I tried to make an analysis of transcripts of goat using SQANTI, but I find there are not gene names corresponding to transcripts  in the output report. I also find some novel isoforms have their own names ,such an 'novelGene_AS' in the 'antisense or genic', while others don't have. I have checked the 'ref-GTF' and 'ref-GENOME FASTA', and I thought they don't have problems. I make a comparision of your example Ipunt.fa and mine, and I found in my Input.fa there are not corresponding chromosomes , they aren't mapped. So I want to know whether the Input.fa  was wrong and how I should do next.
[Question.pptx](https://github.com/Magdoll/SQANTI2/files/3409341/Question.pptx)

**Comment by Magdoll** [comment]
Hi @Wenwen420 ,

I have seen this lack of ref gene name in the past due to GTF format differences.

Can you try running `sqanti_qc2.py` with the option `--geneid`?

-Liz

**Comment by Magdoll** [comment]
Close until further notice.
