### ISSUE TITLE
TypeError on v3.2

### ISSUE THREAD

**Issue by kiekyon** [Magdoll/SQANTI2#22]
Hi Magdoll,

I ran your updated version of SQANTI2 v3.2 with script below

> python ../../../SQANTI2/sqanti_qc2.py \
>  -t 50 \
>  test.fasta \
>  ../../../references/gencode.v31.annotation.gtf.gz \
>  ../../../references/hg38_noALT.fa

and encountered the following errors - 

**** Performing Classification of Isoforms....
Traceback (most recent call last):
  File "../../../SQANTI2/sqanti_qc2.py", line 1677, in <module>
    main()
  File "../../../SQANTI2/sqanti_qc2.py", line 1673, in main
    run(args)
  File "../../../SQANTI2/sqanti_qc2.py", line 1325, in run
    isoforms_info = isoformClassification(args, isoforms_by_chr, refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene, genome_dict, indelsJunc, orfDict)
  File "../../../SQANTI2/sqanti_qc2.py", line 1225, in isoformClassification
    dist_to_last_junc = rec.junctions[0][1] - orfDict[rec.id].cds_genomic_end
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

Do you have any suggestions to fix the error?
The same command work fine previously on v2.8.

**Comment by Magdoll** [comment]
I'm aware of this bug...currently working on it.
v3.2 added new NMD detection and has been running into several boundaries cases which I'm solving now

**Comment by Magdoll** [comment]
Hi,

I am aware of this issue and this is becuz of several dependency updates.

Please update to SQANTI2 v3.5
Please update Cupcake to v8.1
Please install gffread and gtfToGenePred using BioConda
```
conda install -n anaCogent3 -c bioconda ucsc-gtftogenepred openssl=1.0
conda install -n anaCogent3 -c bioconda gffread
```
