### ISSUE TITLE
AttributeError running squanti2

### ISSUE THREAD

**Issue by qoiopipq** [Magdoll/SQANTI2#25]
I just installed the latest version of SQANTI2, and had this error: 
Traceback (most recent call last):
  File "SQANTI2-master/sqanti_qc2.py", line 66, in <module>
    v1, v2 = map(int, cupcake.__version__.split('.'))
AttributeError: 'module' object has no attribute '__version__'

**Comment by Magdoll** [comment]
Hi @qoiopipq ,
Your [Cupcake](https://github.com/Magdoll/cDNA_Cupcake) probably needs to be updated.

--Liz

**Comment by qoiopipq** [comment]
it works!  Thanks!
