### ISSUE TITLE
Caution: long input filenames create unrelated error messages

### ISSUE THREAD

**Issue by markb729** [Magdoll/SQANTI2#26]
Hi Elizabeth, 

When using sqanti_qc2.py, if the filename of the input fasta file is sufficiently long (and possibly including the path too), GeneMark will throw an error.

> Error on open output file /mnt/data/IsoSeq_20190729/GMST/GMST_tmp
GeneMarkS: error on last system call, error code 256
Abort program!!!

Examination of the GeneMark log file suggests that gmst.pl is happy, but probuild is not:

> /mnt/data/IsoSeq_20190729/SQANTI2/utilities/gmst/probuild --par /mnt/data/IsoSeq_20190729/SQANTI2/utilities/gmst/par_1.default --clean_join sequence --seq /mnt/data/IsoSeq_20190729/m54178_190723_19024
0.ccs.demux.primer_5p--primer_3p_flnc_polished_CUPCAKE.collapsed.rep.renamed_corrected.fasta --log gms.log
Error on last system call, error code 256
Abort program!!!

Direct invocation of probuild yields the following uninformative error:

> error in command line

This feature is clearly related to GeneMark and not SQANTI2. Nevertheless, keeping the length of input filenames to a minimum solves this issue.

Sincerely,
Mark

**Comment by Magdoll** [comment]
Hi @markb729 ,
How long was your filename?

**Comment by markb729** [comment]
I have not tested the minimum number required to throw an error, but 94 characters without the path (or 136 with the path) will cause the error.

**Comment by anilkanthi** [comment]
Hi @markb729 
This was helpful! Wouldn't have thought the errors were due to the filename length.. @Magdoll Would it be possible to fix this as even the most recent version faced the issue?
Thank you.
