### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by tay45** [Magdoll/SQANTI2#27]
Hello,

I had an error (subprocess.CalledProcessError) when I ran the SQANTI2 (v3.5.1). I attached the log at below. Could you please give me an advice how to resolve it? Thank you!

Taehee

--------------------------------------

sqanti_qc2.py -t 30 collapse.collapsed.rep.fq gencode.v30.annotation.gtf GRCh38.p12.genome.fa --cage_peak hg38.cage_peak_phase1and2combined_coord.bed --coverage intropolis.v1.hg19_with_liftover_to_hg38.tsv.min_count_10.modified --fl_count collapse.collapsed.abundance.txt

R scripting front-end version 3.5.1 (2018-07-02)
Cleaning up isoform IDs...
Cleaned up isoform fasta file written to: /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/nalm6k/collapse/collapse.collapsed.rep.renamed.fasta
[M::mm_idx_gen::83.946*1.76] collected minimizers
[M::mm_idx_gen::94.838*3.25] sorted minimizers
[M::main::94.839*3.25] loaded/built the index for 593 target sequence(s)
[M::mm_mapopt_update::100.084*3.13] mid_occ = 803
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 593
[M::mm_idx_stat::102.354*3.08] distinct minimizers: 167309999 (34.26% are singletons); average occurrences: 6.324; average spacing: 3.074
[M::worker_pipeline::115.089*5.66] mapped 23933 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -ax splice --secondary=no -C5 -uf -t 30 /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/GRCh38.p12.genome.fa /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/nalm6k/collapse/collapse.collapsed.rep.renamed.fasta
[M::main] Real time: 115.208 sec; CPU: 651.074 sec; Peak RSS: 23.933 GB
output written to /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/nalm6k/test/collapse.collapsed.rep.renamed_corrected.fasta
**** Parsing Isoforms....
Input pattern: /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/intropolis/intropolis.v1.hg19_with_liftover_to_hg38.tsv.min_count_10.modified. The following files found and to be read as junctions:
/net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/intropolis/intropolis.v1.hg19_with_liftover_to_hg38.tsv.min_count_10.modified
5041602 junctions read. 0 junctions added to both strands because no strand information from STAR.
**** RT-switching computation....
**** Reading Full-length read abundance files...
WARNING: PB.6189.1.gene not found in FL count file. Assign count as 0.
WARNING: PB.5162.3.gene not found in FL count file. Assign count as 0.
WARNING: PB.7490.1.gene not found in FL count file. Assign count as 0.
.
.
.
WARNING: PB.7367.10.gene not found in FL count file. Assign count as 0.
WARNING: PB.2750.7.gene not found in FL count file. Assign count as 0.
WARNING: PB.4315.1.gene not found in FL count file. Assign count as 0.
Isoforms expression files not provided.
**** Writing output files....
**** Generating SQANTI report....

Attaching package: ‘dplyr’

The following object is masked from ‘package:gridExtra’:

    combine

The following object is masked from ‘package:reshape’:

    rename

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Warning messages:
1: Removed 1 rows containing missing values (geom_text). 
2: Removed 1 rows containing missing values (geom_bar). 
3: Removed 1 rows containing missing values (geom_text). 
Error: StatBin requires a continuous x variable: the x variable is discrete. Perhaps you want stat="count"?
Execution halted
**** Running SQANTI...
**** Parsing provided files....
Reading genome fasta /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/GRCh38.p12.genome.fa....
****Aligning reads with Minimap2...
**** Predicting ORF sequences...
**** Parsing Reference Transcriptome....
**** Reading Splice Junctions coverage files.
**** Reading CAGE Peak data.
**** Performing Classification of Isoforms....
Number of classified isoforms: 47866
Traceback (most recent call last):
  File "/opt/SQANTI2/20190618/bin/sqanti_qc2.py", line 1717, in <module>
    main()
  File "/opt/SQANTI2/20190618/bin/sqanti_qc2.py", line 1713, in main
    run(args)
  File "/opt/SQANTI2/20190618/bin/sqanti_qc2.py", line 1531, in run
    if subprocess.check_call(cmd, shell=True)!=0:
  File "/opt/SQANTI2/20190618/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/SQANTI2/20190618/bin/Rscript /opt/SQANTI2/20190618/bin/utilities//SQANTI_report2.R /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/nalm6k/test/collapse.collapsed.rep_classification.txt /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/nalm6k/test/collapse.collapsed.rep_junctions.txt' returned non-zero exit status 1

**Comment by ralanharris** [comment]
I am encountering the same "Error: StatBin requires a continuous x variable: the x variable is discrete. Perhaps you want stat="count"?" error.

**Comment by Magdoll** [comment]
Hi @xogur @ralanharris 

Sorry this was an error that happens when polyA info is `NA`. Should be fixed in the latest version v3.8.
--Liz

**Comment by tay45** [comment]
Thank you Liz! 

But, I have had another error. Please see my log at below.

Taehee

--------------------------------------------------

R scripting front-end version 3.5.1 (2018-07-02)
Cleaning up isoform IDs...
Cleaned up isoform fasta file written to: /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/nalm6k/collapse/collapse.collapsed.rep.renamed.fasta
[M::mm_idx_gen::88.849*1.81] collected minimizers
[M::mm_idx_gen::102.278*3.36] sorted minimizers
[M::main::102.279*3.36] loaded/built the index for 593 target sequence(s)
[M::mm_mapopt_update::107.933*3.23] mid_occ = 803
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 593
[M::mm_idx_stat::110.185*3.19] distinct minimizers: 167309999 (34.26% are singletons); average occurrences: 6.324; average spacing: 3.074
[M::worker_pipeline::124.803*5.59] mapped 23933 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -ax splice --secondary=no -C5 -uf -t 30 /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/GRCh38.p12.genome.fa /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/nalm6k/collapse/collapse.collapsed.rep.renamed.fasta
[M::main] Real time: 125.185 sec; CPU: 697.785 sec; Peak RSS: 24.141 GB
output written to /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/nalm6k/test/collapse.collapsed.rep.renamed_corrected.fasta
**** Parsing Isoforms....
Input pattern: /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/intropolis/intropolis.v1.hg19_with_liftover_to_hg38.tsv.min_count_10.modified. The following files found and to be read as junctions:
/net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/intropolis/intropolis.v1.hg19_with_liftover_to_hg38.tsv.min_count_10.modified
5041602 junctions read. 0 junctions added to both strands because no strand information from STAR.
**** RT-switching computation....
**** Reading Full-length read abundance files...
**** Running SQANTI...
**** Parsing provided files....
Reading genome fasta /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/GRCh38.p12.genome.fa....
****Aligning reads with Minimap2...
**** Predicting ORF sequences...
**** Parsing Reference Transcriptome....
**** Reading Splice Junctions coverage files.
**** Reading CAGE Peak data.
**** Performing Classification of Isoforms....
Number of classified isoforms: 47866
Traceback (most recent call last):
  File "/opt/SQANTI2/20190618/bin/sqanti_qc2.py", line 1759, in <module>
    main()
  File "/opt/SQANTI2/20190618/bin/sqanti_qc2.py", line 1755, in main
    run(args)
  File "/opt/SQANTI2/20190618/bin/sqanti_qc2.py", line 1433, in run
    fl_samples, fl_count_dict = FLcount_parser(args.fl_count)
  File "/opt/SQANTI2/20190618/bin/sqanti_qc2.py", line 1366, in FLcount_parser
    samples.remove('superPBID')
ValueError: list.remove(x): x not in list

**Comment by Magdoll** [comment]
Hi @xogur,

Apologies. Fixed this in v3.9. Please confirm.

--Liz

**Comment by tay45** [comment]
Hi Liz,

Thank you for your help!

No error message has occurred. But, there are many warnings regarding FL counts. It seems the fl_count wasn't working. The fl counts were in my abundance file. But, SQANTI2 couldn't find them. I attached the log at below. Thank you!

Taehee
--------------------------
R scripting front-end version 3.5.1 (2018-07-02)
Cleaning up isoform IDs...
Cleaned up isoform fasta file written to: /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/nalm6k/collapse/collapse.collapsed.rep.renamed.fasta
[M::mm_idx_gen::82.845*1.85] collected minimizers
[M::mm_idx_gen::95.033*3.41] sorted minimizers
[M::main::95.035*3.41] loaded/built the index for 593 target sequence(s)
[M::mm_mapopt_update::100.080*3.29] mid_occ = 803
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 593
[M::mm_idx_stat::102.125*3.25] distinct minimizers: 167309999 (34.26% are singletons); average occurrences: 6.324; average spacing: 3.074
[M::worker_pipeline::116.836*5.83] mapped 23933 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -ax splice --secondary=no -C5 -uf -t 30 /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/GRCh38.p12.genome.fa /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/nalm6k/collapse/collapse.collapsed.rep.renamed.fasta
[M::main] Real time: 117.146 sec; CPU: 681.209 sec; Peak RSS: 23.600 GB
output written to /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/nalm6k/test/collapse.collapsed.rep.renamed_corrected.fasta
**** Parsing Isoforms....
Input pattern: /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/intropolis/intropolis.v1.hg19_with_liftover_to_hg38.tsv.min_count_10.modified. The following files found and to be read as junctions:
/net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/intropolis/intropolis.v1.hg19_with_liftover_to_hg38.tsv.min_count_10.modified
5041602 junctions read. 0 junctions added to both strands because no strand information from STAR.
**** RT-switching computation....
**** Reading Full-length read abundance files...
Single-sample PacBio FL count format detected.
WARNING: PB.6189.1.gene not found in FL count file. Assign count as 0.
WARNING: PB.5162.3.gene not found in FL count file. Assign count as 0.
WARNING: PB.7490.1.gene not found in FL count file. Assign count as 0.
.
.
.
WARNING: PB.7367.10.gene not found in FL count file. Assign count as 0.
WARNING: PB.2750.7.gene not found in FL count file. Assign count as 0.
WARNING: PB.4315.1.gene not found in FL count file. Assign count as 0.
Isoforms expression files not provided.
**** Writing output files....
**** Generating SQANTI report....

Attaching package: ‘dplyr’

The following object is masked from ‘package:gridExtra’:

    combine

The following object is masked from ‘package:reshape’:

    rename

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Warning messages:
1: Removed 1 rows containing missing values (geom_text). 
2: Removed 1 rows containing missing values (geom_bar). 
3: Removed 1 rows containing missing values (geom_text). 
null device 
          1 
[1] "SQANTI report successfully generated!"
Removing temporary files....
SQANTI complete in 740.995995045 sec.
**** Running SQANTI...
**** Parsing provided files....
Reading genome fasta /net/isi-dcnl/ifs/user_data/Seq/PacBio/thkang/lili_wang_iso-seq/GRCh38.p12.genome.fa....
****Aligning reads with Minimap2...
**** Predicting ORF sequences...
**** Parsing Reference Transcriptome....
**** Reading Splice Junctions coverage files.
**** Reading CAGE Peak data.
**** Performing Classification of Isoforms....
Number of classified isoforms: 47866

**Comment by Magdoll** [comment]
It looks like the gene ID in your input (did you give the input isoforms in fasta or gff?) had the IDs mutated to `PB.6189.1.gene` when it should be `PB.6189.1` so it's not matching the FL count files.

Can you confirm what your input is? Fasta? GFF? 

There is another issue pointing out issues with some part of the code adding `.gene` suffix. I may have to look into this potential bug.

-Liz

**Comment by tay45** [comment]
My input was the fasta.

Thank you,

Taehee

**Comment by Magdoll** [comment]
Hi @xogur ,

I tried to duplicate the result and I think it may have something to do with older versions of SQANTI2....

Would you mind updating to the latest SQANTI2 and running a "clean" new run? (don't reuse the directory because SQANTI2 will pick up older existing files to re-use)

If it still has issues, I will ask for your input files confidentially to test.

--Liz

**Comment by tay45** [comment]
Hello Liz,

The error was the same. I have emailed my input files. Thank you!

Taehee

**Comment by Magdoll** [comment]
Hi @xogur ,

I ran it with SQANTI2 v4.0 with the following commands and no errors were found.

```
python <path_to>/sqanti_qc2.py -t 30 collapse.collapsed.rep.fasta \
     gencode.v29.annotation.gtf hg38.fa \
     --fl_count collapse.collapsed.abundance.txt
```

I uploaded some of the SQANTI2 output here: https://www.dropbox.com/sh/dcy9nh3yi6oushz/AADKzVtRpG7gUkLlrxiD2O8Ra?dl=0

--Liz

**Comment by tay45** [comment]
Thank you Liz!

It is working now. We have changed R version from 3.5 down to 3.4.3. It looks like version of those specific packages under R matter.

Taehee
