### ISSUE TITLE
some Questions about the results

### ISSUE THREAD

**Issue by shangguandong1996** [Magdoll/SQANTI2#28]
Hi, Magdoll.
I follow the Iso-Seq3 -> Cupcake ToFU -> SQATNI pipeline. I have some question about the sqanti result.
First,I noticed the result in XX.collapsed.rep.renamed_corrected.gtf is like
```
transcript_id "PB.1.1"; gene_id "PB.1.1";
```
instead of 
```
transcript_id "PB.1.1"; gene_id "PB.1";
```

Second, I found no gtf output after I run sqanti_filter2.py although I can grep filterd gene in corrected.gtf to make filter.gtf.

Thanks for you pipeline. These are very helpful !

**Comment by Magdoll** [comment]
Hi @shangguandong1996 ,

The latest (v4.0) now outputs GTF with `sqanti_filter2.py` please give it a try.

Thanks,
-Liz
