### ISSUE TITLE
will SQANTI2 works on custom fasta file?

### ISSUE THREAD

**Issue by LuyiTian** [Magdoll/SQANTI2#31]
My fasta file is not the ouput from pacbio (from nanopore instead). and I got the error as such: 

`Invalid input IDs! Expected PB.X.Y or PB.X.Y|xxxxx or PBfusion.X format but saw ENSG00000197956.9_153534599_153535991_1 instead. Abort!`

is it possibly to use custom fasta file as input for SQANTI2?

**Comment by Magdoll** [comment]
Hi @LuyiTian ,

We require SQANTI2 input to have a particular sequence ID format. If you'd like to use other kinds of input data, you would have to alter the sequence IDs.

Thanks,
--Liz

**Comment by caocaoBioInfo** [comment]
> Hi @LuyiTian ,
> 
> We require SQANTI2 input to have a particular sequence ID format. If you'd like to use other kinds of input data, you would have to alter the sequence IDs.
> 
> Thanks,
> --Liz

how can we do that ?such as scipt or something?
Thanks

**Comment by Magdoll** [comment]
Hi please move to using [SQANTI3](https://github.com/ConesaLab/SQANTI3). SQANTI2 is deprecated.
-Liz
