### ISSUE TITLE
Error when running SQANTI2

### ISSUE THREAD

**Issue by Treywea** [Magdoll/SQANTI2#32]
Hi There!

Just get an error by : python sqanti_qc2.py -t 30 <fasta> <gtf> <reference>

Here is what script return: 
Traceback (most recent call last):
  File "sqanti_qc2.py", line 117, in <module>
    if os.system(RSCRIPTPATH + " --version")!=0:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

I already check that I fit all prerequisite. Many thanks in advance.

**Comment by Magdoll** [comment]
Hi @Treywea ,

Can you check that you have the `Rscript` executable command available? This is probably the source of the error. 

```
$ Rscript
Usage: /path/to/Rscript [--options] [-e expr [-e expr2 ...] | file] [args]

--options accepted are
  --help              Print usage and exit
  --version           Print version and exit
  --verbose           Print information on progress
  --default-packages=list
                      Where 'list' is a comma-separated set
                        of package names, or 'NULL'
or options to R, in addition to --slave --no-restore, such as
  --save              Do save workspace at the end of the session
  --no-environ        Don't read the site and user environment files
  --no-site-file      Don't read the site-wide Rprofile
  --no-init-file      Don't read the user R profile
  --restore           Do restore previously saved objects at startup
  --vanilla           Combine --no-save, --no-restore, --no-site-file
                        --no-init-file and --no-environ
```
-Liz

**Comment by Treywea** [comment]
Many thanks for the reply. I solve the problem after re-install the r-base-core. Thanks

Qianwen
