### ISSUE TITLE
A question about "associated_gene" from _classification.txt

### ISSUE THREAD

**Issue by yejilee-biostat** [Magdoll/SQANTI2#34]
Hi Elizabeth,

 I am sorry for asking a question rather than reporting an error here (I can't find another way to contact you). 

 When I see an "associated_gene" columns from a result file ( *_classification.txt ), sometime I can see two gene names are connected by underscore ("_"), which isn't in the reference. First I thought it could mean a fused gene, but it said "genic" at structural_category, not "fusion", so I am not sure how to interpret this. Could you please explain what these types of "associated genes" means? Thanks a lot!

**Comment by Magdoll** [comment]
Hi @yejilee-biostat ,

Thank you for contacting me. 

It is possible to overlap multiple reference genes. In these cases SQANTI2 uses the "_" symbol to connect them.

Let me know if this clarifies it - if there appears to be a bug in the classification, please provide the transcript sequence that caused this issue so I can fix it.

p.s. while this is the right place to ask about SQANTI2, I also encourage you to join the public Iso-Seq google group to stay up to date on other matters. 
https://groups.google.com/forum/#!forum/smrt_isoseq


--Liz

**Comment by yejilee-biostat** [comment]
Hi Liz,

 Thanks a lot! I think it must be multiple genes as you said.
 I will look through this again and if it seems a bug, then I will definitely reply to this post again.

edit) It seems there is no error - thanks for your kind reply again!

Best,
Yeji
