### ISSUE TITLE
Could I use BAM as input rather than FASTQ?

### ISSUE THREAD

**Issue by juheon** [Magdoll/SQANTI2#37]
I know the current version of SQANTI2 does not support BAM as input. It uses FASTQ files and runs the alignment. If I want to do some post-alignment filtering before SQANTI2, what I need to do is 1) align FLNC reads on my own, 2) do post-alignment filtering, 3) convert bam to FASTQ, 4) run SQANTI2 which comes with an additional round of alignment using filtered FASTQ. 
  This is more issue since I use FLNC reads rather clustered reads and I need more post-processing for FLNC reads. For my research, the number of PacBio reads matters to assess the expression of isoforms. Moreover, the clustering procedure discards singleton transcripts which is the evidence of expression of rare isoforms. 
  Would it be possible to use BAM as input for SQANTI2?

**Comment by Magdoll** [comment]
Hi @juheon ,

I will put BAM/SAM support as a possible future support.

In the meantime, you can convert the SAM/BAM alignment into GTF/GFF3 and use `--gtf` as input. This way, SQANTI2 will not run aligner again.


--Liz

**Comment by juheon** [comment]
Hi, I used "sam_to_gff3.py" of cDNAcupcake to generate gff from bam file and ran "python sqanti_qc2.py -t 4 --skipORF --gtf [gff] [gencode gtf] [hg38.fa]". However, it returned the following error. I think the error is due to the lack of "transcript" line in the gff3. Is "sam_to_gff3.py" not appropriate for converting sam to gff for SQANTI2? If not, do you have recommended tools for sam/bam to gff conversion for SQANTI2?

`Traceback (most recent call last):
  File "/bar/jmaeng/pfiles/SQANTI2/sqanti_qc2.py", line 1793, in <module>
    main()
  File "/bar/jmaeng/pfiles/SQANTI2/sqanti_qc2.py", line 1789, in main
    run(args)
  File "/bar/jmaeng/pfiles/SQANTI2/sqanti_qc2.py", line 1436, in run
    write_collapsed_GFF_with_CDS(isoforms_info, corrGTF, corrGTF+'.cds.gff')
  File "/bar/jmaeng/pfiles/SQANTI2/sqanti_qc2.py", line 400, in write_collapsed_GFF_with_CDS
    for r in reader:
  File "/opt/apps/cDNA_Cupcake/cDNA_Cupcake/cDNA_Cupcake-Py2_v8.7.x/cupcake/io/GFF.py", line 395, in next
    return self.read()
  File "/opt/apps/cDNA_Cupcake/cDNA_Cupcake/cDNA_Cupcake-Py2_v8.7.x/cupcake/io/GFF.py", line 552, in read
    assert raw[2] == 'transcript'
AssertionError`

My script version is
SQANTI2 4.1
cDNA_Cupcake-Py2_v8.7.x
