### ISSUE TITLE
sqanti_filter2.py is not working

### ISSUE THREAD

**Issue by tay45** [Magdoll/SQANTI2#40]
Hello,

The sqanti_qc2.py is working, but sqanti_filter2.py isn't as below. It seems to be the python script issue? I will appreciate it if you will help me to fix the problem. Thank you!

Taehee

---------------------------------------------------- 

$ sqanti_filter2.py
/opt/SQANTI2/20190822/envs/anaCogent3/bin/sqanti_filter2.py: line 1: __author__: command not found
/opt/SQANTI2/20190822/envs/anaCogent3/bin/sqanti_filter2.py: line 2: __version__: command not found
/opt/SQANTI2/20190822/envs/anaCogent3/bin/sqanti_filter2.py: line 12: 
Lightweight filtering of SQANTI by using .classification.txt output

Only keep Iso-Seq isoforms if:
The isoform is FSM, ISM, or NIC and (does not have intrapriming or has polyA_motif)
The isoform is NNC, does not have intrapriming/or polyA motif, not RT-switching, and all junctions are either all canonical or short-read-supported
The isoform is antisense, intergenic, genic, does not have intrapriming/or polyA motif, not RT-switching, and all junctions are either all canonical or short-read-supported

: No such file or directory
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
/opt/SQANTI2/20190822/envs/anaCogent3/bin/sqanti_filter2.py: line 16: from: command not found
/opt/SQANTI2/20190822/envs/anaCogent3/bin/sqanti_filter2.py: line 17: from: command not found
/opt/SQANTI2/20190822/envs/anaCogent3/bin/sqanti_filter2.py: line 18: from: command not found
/opt/SQANTI2/20190822/envs/anaCogent3/bin/sqanti_filter2.py: line 19: from: command not found
/opt/SQANTI2/20190822/envs/anaCogent3/bin/sqanti_filter2.py: line 21: syntax error near unexpected token `('
/opt/SQANTI2/20190822/envs/anaCogent3/bin/sqanti_filter2.py: line 21: `utilitiesPath =  os.path.dirname(os.path.realpath(__file__))+"/utilities/"'

**Comment by Magdoll** [comment]
Hi @xogur ,

PLease do `python sqanti_filter2.py` instead of directly executing the script.

**Comment by tay45** [comment]
Thank you!

2019년 10월 8일 (화) 오후 2:08, Elizabeth Tseng <notifications@github.com>님이 작성:
