### ISSUE TITLE
More specific instructions installing cDNA_cupcake

### ISSUE THREAD

**Issue by astrophys** [Magdoll/SQANTI2#41]
FYI, it appears that recently, [cDNA_Cupcake](https://github.com/Magdoll/cDNA_Cupcake/tree/Py2_v8.7.x) created a python 2.7 branch.  The most recent master only supports python 3.7.  In your installation instructions, perhaps suggest  after cloning the repo changing to the 2.7 branch? 

E.g. 

```
cd cDNA_Cupcake
git checkout origin/Py2_v8.7.x
python setup.py build
 pip install --prefix=/some/path/cDNA_Cupcake/ --ignore-installed .
```

Best,
Ali

**Comment by Magdoll** [comment]
Hi @astrophys ,

Yes, thanks for the reminder. Sorry currently there are two versions - I'm hoping to fully switch to Py3.7 in a bit. For now, Py2.7 is kept as legacy. I have updated the wiki instructions.
-Liz
