### ISSUE TITLE
How to generate a short read expression file?

### ISSUE THREAD

**Issue by qoiopipq** [Magdoll/SQANTI2#44]
I've a question about using RSEM to quantify Iso-Seq collapsed long reads by RNA-seq short reads, then use it as a short read expression file for running SQANTI2. Sorry if here is not the place to discuss it.
As SQANTI paper stated that it can take Iso-Seq + RNA-seq as input. My understanding is to use the Iso-Seq collapsed long transcripts as reference then map short reads against using RSEM (or other tools). According to RSEM, it requires reference sequences using (rsem-prepare-reference command). I tried to run this command to build collapsed long reads as the reference, but it didn't work. For all the options in RSEM preparing reference step, I don't think which one should be used. If anyone can provide the commands or options that will be great.

For the Iso-Seq pipeline, I've GMAP aligned files, ToFu collpased transcripts, and for RNA-seq, paired end reads.

Cheers!

**Comment by Br1anChou** [comment]
Hi @qoiopipq @Magdoll ,
I have the same problem. How did you solve it?
I used the software RSEM.
Best!
