### ISSUE TITLE
[v5.1.0]  Error: invalid feature coordinates (end<start!)

### ISSUE THREAD

**Issue by yejilee-biostat** [Magdoll/SQANTI2#47]
Hello @Magdoll ,

 I've tried the newest version of SQANTI2 (v5.1.0) and saw the following log:

`[M::main] Version: 2.17-r941`
`[M::main] CMD: minimap2 -ax splice -uf -k14 -C5 --secondary=no -t 50 hg38_chr.fa file1.fasta `
`[M::main] Real time: 1452.274 sec; CPU: 68896.896 sec; Peak RSS: 54.618 GB`
`Error: invalid feature coordinates (end<start!) at line:`
`chr5    hg38_chr        exon    40824922        40824921        .       -       .       ID=94a3dcb5-de7c-4d08-b571-e2d0c5533afa_dup2.exon2;Name=94a3dcb5-de7c-4d08-b571-e2d0c5533afa_dup2.exon2;Parent=94a3dcb5-de7c-4d08-b571-e2d0c5533afa_dup2`
`Error: invalid feature coordinates (end<start!) at line:`
`chr2    hg38_chr        exon    88935909        88935908        .       -       .       ID=65ccca1d-b8ee-40ef-9b7a-2a617adf3cfe.exon2;Name=65ccca1d-b8ee-40ef-9b7a-2a617adf3cfe.exon2;Parent=65ccca1d-b8ee-40ef-9b7a-2a617adf3cfe`

I've modified the minimap2 option for Nanopore direct RNA, but didn't change anything. there are only 4 lines saying "invalid feature coordinates", but it bothers me nonetheless. Could you help me on understanding what's going on? Thanks!

**Comment by Magdoll** [comment]
Hi @yejilee-biostat ,

This is not a SQANTI2 error but an issue with minimap2 output. Notice that in the GFF there are exon coordinates where the start is greater than the end.

```
chr2 hg38_chr exon 88935909 88935908 
```

The offending exon coordinates have to be fixed before running SQANTI2

--Liz

**Comment by xue-222** [comment]
How can this problem be solved?

**Comment by Magdoll** [comment]
SQANTI2 is no longer supported. PLease use either [SQANTI3](https://github.com/ConesaLab/SQANTI3) or [pigeon](https://isoseq.how/classification/)

**Comment by xue-222** [comment]
ok,thank you
