### ISSUE TITLE
Existing files from "incomplete" runs cause errors on subsequent runs

### ISSUE THREAD

**Issue by wolfgangrumpf** [Magdoll/SQANTI2#49]
I'm in the middle of prepping a script to perform this analysis, and I'd forgotten to enable the gmap module on my system - so sqanti kind of ran but didn't.  Subsequently, it continued to fail until I deleted the files that were created during the aborted attempt - apparently it doesn't like having pre-existing files:

**** Predicting ORF sequences...
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_S_create
GeneMarkS: error on last system call, error code 134
Abort program!!!
Traceback (most recent call last):
  File "/opt/sqanti2/4.1/SQANTI2-4.1/sqanti_qc2.py", line 1793, in <module>
    main()
  File "/opt/sqanti2/4.1/SQANTI2-4.1/sqanti_qc2.py", line 1789, in main
    run(args)
  File "/opt/sqanti2/4.1/SQANTI2-4.1/sqanti_qc2.py", line 1414, in run
    orfDict = correctionPlusORFpred(args, genome_dict)
  File "/opt/sqanti2/4.1/SQANTI2-4.1/sqanti_qc2.py", line 555, in correctionPlusORFpred
    if subprocess.check_call(cmd, shell=True, cwd=gmst_dir)!=0:
  File "/opt/sqanti2/4.1/anaCogent3/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'perl /gpfs0/export/opt/sqanti2/4.1/SQANTI2-4.1/utilities/gmst/gmst.pl -faa --strand direct --fnn --output /gpfs0/home/gdlauberlab/rwr002/TESTING/ISOSEQ_2/GMST/GMST_tmp /gpfs0/home/gdlauberlab/rwr002/TESTING/ISOSEQ_2/cupcake.gmap.collapsed.rep.renamed_corrected.fasta' returned non-zero exit status 1

**Comment by Magdoll** [comment]
HI @wolfgangrumpf ,
Yes you need to clean up the old - half failed directories. That said, SQANTI2 was designed to re-use existing files, often because this will save time, esp in regards to ORF prediction.

-Liz
