### ISSUE TITLE
python: can't open file 'sqanti_qc2.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by laguda-1996** [Magdoll/SQANTI2#50]
Hello, I have an installation problem.Any help will be appreciated.
I installed it according to the process,but when I type  python sqanti_qc2.py , terminal display a error that  python: can't open file 'sqanti_qc2.py': [Errno 2] No such file or directory
after type  python setup.py install ,the  terminal display:

Installing out_to_chain.py script to /home/dsy/anaconda3/envs/sqanti2/bin
Installing bed_count_overlapping.py script to /home/dsy/anaconda3/envs/sqanti2/bin
Installing wiggle_to_array_tree.py script to /home/dsy/anaconda3/envs/sqanti2/bin
Installing tfloc_summary.py script to /home/dsy/anaconda3/envs/sqanti2/bin
Installing maf_interval_alignibility.py script to /home/dsy/anaconda3/envs/sqanti2/bin
Installing maf_thread_for_species.py script to /home/dsy/anaconda3/envs/sqanti2/bin
Installing maf_print_scores.py script to /home/dsy/anaconda3/envs/sqanti2/bin
Installing prefix_lines.py script to /home/dsy/anaconda3/envs/sqanti2/bin
Installing maf_col_counts.py script to /home/dsy/anaconda3/envs/sqanti2/bin
Installing interval_join.py script to /home/dsy/anaconda3/envs/sqanti2/bin
Installing maf_extract_chrom_ranges.py script to /home/dsy/anaconda3/envs/sqanti2/bin
Installing bed_bigwig_profile.py script to /home/dsy/anaconda3/envs/sqanti2/bin
Installing bed_subtract_basewise.py script to /home/dsy/anaconda3/envs/sqanti2/bin
Installing maf_limit_to_species.py script to /home/dsy/anaconda3/envs/sqanti2/bin
Installing bed_diff_basewise_summary.py script to /home/dsy/anaconda3/envs/sqanti2/bin
Installing bed_coverage.py script to /home/dsy/anaconda3/envs/sqanti2/bin
Installing maf_to_axt.py script to /home/dsy/anaconda3/envs/sqanti2/bin
Installing line_select.py script to /home/dsy/anaconda3/envs/sqanti2/bin

Using /home/dsy/anaconda3/envs/sqanti2/lib/python3.7/site-packages/bx_python-0.8.6-py3.7-linux-x86_64.egg
Searching for biopython==1.76
Best match: biopython 1.76
Adding biopython 1.76 to easy-install.pth file

Using /home/dsy/anaconda3/envs/sqanti2/lib/python3.7/site-packages
Searching for scikit-learn==0.22.1
Best match: scikit-learn 0.22.1
Processing scikit_learn-0.22.1-py3.7-linux-x86_64.egg
scikit-learn 0.22.1 is already the active version in easy-install.pth

Using /home/dsy/anaconda3/envs/sqanti2/lib/python3.7/site-packages/scikit_learn-0.22.1-py3.7-linux-x86_64.egg
Searching for six==1.13.0
Best match: six 1.13.0
Adding six 1.13.0 to easy-install.pth file

Using /home/dsy/anaconda3/envs/sqanti2/lib/python3.7/site-packages
Searching for scipy==1.4.1
Best match: scipy 1.4.1
Processing scipy-1.4.1-py3.7-linux-x86_64.egg
scipy 1.4.1 is already the active version in easy-install.pth

Using /home/dsy/anaconda3/envs/sqanti2/lib/python3.7/site-packages/scipy-1.4.1-py3.7-linux-x86_64.egg
Searching for joblib==0.14.1
Best match: joblib 0.14.1
Processing joblib-0.14.1-py3.7.egg
joblib 0.14.1 is already the active version in easy-install.pth

Using /home/dsy/anaconda3/envs/sqanti2/lib/python3.7/site-packages/joblib-0.14.1-py3.7.egg
Finished processing dependencies for cupcake==9.1.1

Does this display indicate that the installation is successful？
Thank you for your help!

**Comment by Magdoll** [comment]
Hi @laguda-1996 ,
SQANTI2 does not require installation (while Cupcake does).
To run `sqanti_qc2.py`, you would directly point to the script location in the GitHub repo.

For example:

```
python /home/user/SQANTI2/sqanti_qc2.py ....
```

**Comment by laguda-1996** [comment]
Thank you very much for your reply！
