### ISSUE TITLE
Possible error from input gff files instead of fasta/fastq/gtf files

### ISSUE THREAD

**Issue by leosfan** [Magdoll/SQANTI2#56]
Hello Elizabeth,

I'm using SQANTI2 v7.4.0 for downstream analysis and qc of pacbio isoseq data.
I got this error when trying to feed isoseq3 collapsed data (gff file) to sqanti_qc2.py:

`
(anaCogent) [root@415f002f77c8 before-SQANTI2filter]# python /root/SQANTI2-7.4.0/sqanti_qc2.py -t 30 -n 10 --polyA_peak ../../db/hg38.polyA_sites.bed --fl ../algin_collapse/mc_cell_line.collapsed.abundance.txt --polyA_motif_list ../../db/human.polyA.list.txt --cage_peak ../../db/hg38.cage_peak_phase1and2combined_coord.bed -c ../../db/intropolis.v1.hg19_with_liftover_to_hg38.tsv.min_count_10.modified ../algin_collapse/mc_cell_line.collapsed.gff ../../db/gtf/gencode.v33.chr_patch_hapl_scaff.annotation.gtf ../../db/GRCh38.p13.genome.fa
R scripting front-end version 3.6.0 (2019-04-26)
Cleaning up isoform IDs...
Cleaned up isoform fasta file written to: /mnt/data/data/algin_collapse/mc_cell_line.collapsed.renamed.fasta
Write arguments to /mnt/data/data/before-SQANTI2filter/mc_cell_line.collapsed.params.txt...
`
**** Running SQANTI2...
**** Generating SQANTI2 report....

Attaching package: 'dplyr'

The following object is masked from 'package:gridExtra':

    combine

The following object is masked from 'package:reshape':

    rename

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union
`
Error in read.table(class.file, header = T, as.is = T, sep = "\t") :
  no lines available in input
Execution halted
Traceback (most recent call last):
  File "/root/SQANTI2-7.4.0/sqanti_qc2.py", line 2198, in <module>
    main()
  File "/root/SQANTI2-7.4.0/sqanti_qc2.py", line 2194, in main
    combine_split_runs(args, split_dirs)
  File "/root/SQANTI2-7.4.0/sqanti_qc2.py", line 2063, in combine_split_runs
    if subprocess.check_call(cmd, shell=True)!=0:
  File "/root/anaconda3/envs/anaCogent/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/bin/Rscript /root/SQANTI2-7.4.0/utilities/SQANTI_report2.R /mnt/data/data/before-SQANTI2filter/mc_cell_line.collapsed_classification.txt /mnt/data/data/before-SQANTI2filter/mc_cell_line.collapsed_junctions.txt /mnt/data/data/before-SQANTI2filter/mc_cell_line.collapsed.params.txt' returned non-zero exit status 1.
`
Anaconda3 env:
Python 3.7.4

Other env settings:
minimap2 2.17-r941
SQANTI2 v7.4.0
cDNA_Cupcake v10.0.1
CentOS 7

I orginally thought to try this fix, but I still got the same error:
`utilitiesPath =  os.path.dirname(os.path.realpath(__file__))+"/utilities/" `
Here, the slash before 'utilities/' seems not useful, since later in the code it provided a slash for assigning the path of `RSCRIPT_REPORT`.
`cmd = RSCRIPTPATH + " {d}/{f} {c} {j} {p}".format(d=utilitiesPath, f=RSCRIPT_REPORT, c=outputClassPath, j=outputJuncPath, p=args.doc)`

Please let me know if you have more insights. If this is in fact caused by the gff file format, then how can I obtain a fasta/fastq/gtf file after running `collapse_isoforms_by_sam.py` (the default out put is my.collapsed.gff)?

Thank you very much for your help!
Best,
Leo

**Comment by Magdoll** [comment]
Hi @leosfan ,
Can you check the output files are non-empty?

```
/mnt/data/data/before-SQANTI2filter/mc_cell_line.collapsed_classification.txt
/mnt/data/data/before-SQANTI2filter/mc_cell_line.collapsed_junctions.txt
```

**Comment by leosfan** [comment]
Hi @Magdoll ,
Yes, they are indeed empty (verified by cat).

**Comment by Magdoll** [comment]
Hi @leosfan ,
The error thus comes from the fact that your SQANTI2 output is empty! The classification.txt and .junctions.txt files are empty so there's nothing to work with, which is really odd.


Can you share with me your input file `../algin_collapse/mc_cell_line.collapsed.gff`?

I can give you a secure portal to upload confidentially. To do so I will need an email.
-Liz

**Comment by leosfan** [comment]
Hi @Magdoll ,

Thanks for your input, I have worked around this problem by transforming the gff to fasta via gffread (which has solved the problem for now). My email is fan.shiheng@hotmail.com

Thanks again.
Best,
Leo

**Comment by Magdoll** [comment]
@leosfan  you should receive a request to upload file.

**Comment by leosfan** [comment]
I have uploaded the file.

**Comment by Magdoll** [comment]
Hi @leosfan ,
I see the problem. Your GFF is not based on the hg38 reference genome.

For ref annotation and genome you specified Gencode v33 and hg38. However, your GFF coordinates are not based on hg38.

This is why the classification/junction output is empty. It also explains why if you give SQANTI2 fasta as input it works - because if you give it a fasta, SQANTI2 first has to align it to the genome and generate the appropriate GFF.

-Liz

**Comment by leosfan** [comment]
Hi @Magdoll ,

Thank you so much for your help!
I guess now I can close this issue, but I do appreciate more insights if you can recommend me some useful tools for annotating the collapsed file: 
1. Since what I did is using minimap2 to preprocess the isoseq3 clustering file, which is then followed by [cDNA_cupcake collapse script](https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake:-supporting-scripts-for-Iso-Seq-after-clustering-step#collapse). What I can do to improve the pipeline such that the resulting gff is indeed in correct coordinates?
2. The gene name in the output gff from SQANTI2 is not the ones in gencode gtf. How can i annoate them with desired names as well as other description of the genes?

Thanks again.
Best,
Leo

**Comment by Magdoll** [comment]
Hi @leosfan ,
1. using minimap2 to process isoseq3 cluster output is the correct step. The problem was you aligned it to something that was not hg38. If you do that, then you must run SQANTI2 against whatever reference you were using. As long as the genome/annotation is consistent between the minimap2/collapse and SQANTI2, all will be well.

2. What do you mean the gene name is not the same? Oh, you mean it's showing gene names (ex: WASH7P) instead of Ensembl IDs (ex: ENSG00000223972.5)?

**Comment by leosfan** [comment]
Hi @Magdoll ,

The gtf result from using the SQANTI2 filtering, which is after the sqanti2_qc.py processing, is listed below:
`$ cat mc_cell_line.collapsed_classification.filtered_lite.gtf | head`

GL000195.1      PacBio  transcript      42939   86684   .       -       .       gene_id "PB.3"; transcript_id "PB.3.1";
GL000195.1      PacBio  exon    42939   44923   .       -       .       gene_id "PB.3"; transcript_id "PB.3.1";
GL000195.1      PacBio  exon    48955   49119   .       -       .       gene_id "PB.3"; transcript_id "PB.3.1";
GL000195.1      PacBio  exon    86518   86684   .       -       .       gene_id "PB.3"; transcript_id "PB.3.1";
GL000195.1      PacBio  CDS     44724   44923   .       -       .       gene_id "PB.3"; transcript_id "PB.3.1";
GL000195.1      PacBio  CDS     48955   49117   .       -       .       gene_id "PB.3"; transcript_id "PB.3.1";
GL000195.1      PacBio  transcript      43074   86669   .       -       .       gene_id "PB.3"; transcript_id "PB.3.2";
GL000195.1      PacBio  exon    43074   44923   .       -       .       gene_id "PB.3"; transcript_id "PB.3.2";
GL000195.1      PacBio  exon    48955   49119   .       -       .       gene_id "PB.3"; transcript_id "PB.3.2";
GL000195.1      PacBio  exon    86518   86669   .       -       .       gene_id "PB.3"; transcript_id "PB.3.2";

Here, the gene_id as well as the transcript_id are not the ones in the reference annotation. I wonder if this is due to the fact that I didn't use the correct genome for minimap2 mapping?

Best,
Leo
