### ISSUE TITLE
question about generating gff3 file

### ISSUE THREAD

**Issue by rapaJiahe** [Magdoll/SQANTI2#6]
Hello @Magdoll,

I  used SQANTI2 results to update my old gene annotation results. i want to know is there any quick way for me to generate gff3 format annotations based on  SQANTI2 results ?

Best,
Xu

**Comment by Magdoll** [comment]
Hi @rapaJiahe ,

Check out `sam_to_gff3.py` in the [Cupcake repo](https://github.com/Magdoll/cDNA_Cupcake/wiki/Sequence-Manipulation-Wiki). Let me know if it works for you!

--liz

**Comment by rapaJiahe** [comment]
Hi @Magdoll,

i used gmap to algin fasta sequences generated by SQANTI2 filter program and then used sam_to_gff3.py to extract gff3 file,  and the fowllowing is my command lines. it works well. However,  the gff3 file only contain gene, mrna and exon, **no CDS**. is there any way to extract CDS information and add it into the gff3 file?

transcripts to sam:
${path}/gmap -D ./  -d  genome.index  -f samse -n 0 -t 12 -z sense_force  all.polished.hq_classification.filtered_lite.fasta  > hq_isoforms.fastq.sam

sam to gff3
python  sam_to_gff3.py  hq_isoforms.fastq.sam  -s Boleracea

best,
Xu

**Comment by Magdoll** [comment]
Hi,

Unfortunately, I currently have no plans to allow *CDS* information from GMAP into GFF...

--Liz
