### ISSUE TITLE
sqanti_filter.py

### ISSUE THREAD

**Issue by moschmi** [Magdoll/SQANTI2#67]
Liz,
I am following your single cell pipeline with cupcake and it works fine.
Now, I would like to filter out mono-exonic isoforms. For that I want to use sqanti_filter.py.
But it never worked for me.
My error is: 
sqanti_filter2.py: error: unrecognized arguments: anyfile.gtf.
my input is: 
sqanti_output_3pass_BC/B_BM_tot.3pass.sort.flnc.merge5.collapsed_classification.txt
sqanti_output_3pass_BC/B_BM_tot.3pass.sort.flnc.merge5.collapsed_corrected.fasta
mmp2_output_3pass_BC/B_BM_tot.3pass.flnc_BC.fasta.sort.sam
sqanti_output_3pass_BC/B_BM_tot.3pass.sort.flnc.merge5.collapsed_corrected.gtf.

I tried several gff and gtf files made from sqanti_qc.py, collapse_isoform_by_sam.py or even the annotation gtf.
Always the same error.
What am I doing wrongly?
Marcel

**Comment by Magdoll** [comment]
Hi @moschmi ,
the `sqanti_filter2.py` parameters have changed.

please use
```
sqanti_filter2.py [class_file] [fasta] [gtf_file]
```

**Comment by moschmi** [comment]
If I leave out the sam file I get this error:

Traceback (most recent call last):
  File "SQANTI2-master/sqanti_filter2.py", line 222, in <module>
    main()
  File "SQANTI2-master/sqanti_filter2.py", line 217, in main
    sqanti_filter_lite(args)
  File "SQANTI2-master/sqanti_filter2.py", line 64, in sqanti_filter_lite
    while runA < len(r['seq_A_downstream_TTS']):
KeyError: 'seq_A_downstream_TTS'

**Comment by Magdoll** [comment]
@moschmi ,
I think you have an older version of SQANTI2. Can you update to the latest and run sqanti_qc2.py first? That field is missing from the classification result.
-liz

**Comment by moschmi** [comment]
**@magdoll,** 
You're right. Now it works beautifully!
