### ISSUE TITLE
Gene_IDs in GTFs

### ISSUE THREAD

**Issue by moschmi** [Magdoll/SQANTI2#69]
Liz,
how can I get real Gene_IDs in the "corrected.gtf" and after "sqanti_filter2.py" in the "classification.filtered_lite.gtf"? Mine only state "PB".
See example:
chr1	PacBio	transcript	14428	16899	.	-	.	gene_id "PB"; transcript_id "PB.1.2";
chr1	PacBio	exon	14428	14829	.	-	.	gene_id "PB"; transcript_id "PB.1.2";
chr1	PacBio	exon	14970	15038	.	-	.	gene_id "PB"; transcript_id "PB.1.2";
chr1	PacBio	exon	15796	15947	.	-	.	gene_id "PB"; transcript_id "PB.1.2";
chr1	PacBio	exon	16607	16765	.	-	.	gene_id "PB"; transcript_id "PB.1.2";
chr1	PacBio	exon	16858	16899	.	-	.	gene_id "PB"; transcript_id "PB.1.2";

best
Marcel

**Comment by moschmi** [comment]
Partial solution:
I added to "sqanti_qc2.py" --geneid and generated corrected.gtf with geneIDs.
But continuation with "sqanti_filter2.py"  brings back the "PB" gene names.
please help.

**Comment by Magdoll** [comment]
Hi,
SQANTI2 is getting discontinued and replaced with [SQANTI3](https://github.com/ConesaLab/SQANTI3). I will no longer be supporting SQANTI2 bugs from now on. Could you please test SQANTI3 and if the same error occurs - file in Issues at SQANTI3.

Thanks,
-Liz

**Comment by moschmi** [comment]
Thanks Liz, Ill also tried sqanti3. Same problem. Will post my issue there.
