### ISSUE TITLE
Error in sqanti2

### ISSUE THREAD

**Issue by LPeit** [Magdoll/SQANTI2#7]
Hi @Magdoll, 

I was running sqanti2 for the first time and got an error message saying:

**** Parsing Reference Transcriptome....
.../SQANTI2/utilities/gtfToGenePred: error while loading shared libraries: libpng12.so.0: cannot open shared ob                ject file: No such file or directory
Traceback (most recent call last):
  File "SQANTI2/sqanti_qc2.py", line 1395, in <module>
    main()
  File "SQANTI2/sqanti_qc2.py", line 1391, in main
    run(args)
  File "SQANTI2/sqanti_qc2.py", line 1084, in run
    refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene = reference_parser(args, genome_dict.keys())
  File "SQANTI2/sqanti_qc2.py", line 480, in reference_parser
    for r in genePredReader(referenceFiles):
  File "SQANTI2/sqanti_qc2.py", line 90, in __init__
    self.f = open(filename)
IOError: [Errno 2] No such file or directory: '.../refAnnotation_hq_transcripts.genePred'
(sqanti) lena@pgm-Precision-WorkStation-T7500: ... /SQANTI2/utilities/gtfToGenePred: error while loading shared libraries: libpng12.so.0: cannot open shared ob                ject file: No such file or directory
-bash: /SQANTI2/utilities/gtfToGenePred:: No such file or directory

Do I need to provide a reference transcriptome file here?? 
Thanks for your help!

Lena

**Comment by Magdoll** [comment]
Hi,

The error stems from this library issue:

```
libpng12.so.0: cannot open shared object file
```

which results in `.../SQANTI2/utilities/gtfToGenePred` failing to execute.

I don't exactly know what the fix would be other than trying to [install libpng](https://askubuntu.com/questions/978294/how-to-fix-libpng12-so-0-cannot-open-shared-object-file-no-such-file-or-direc)
