### ISSUE TITLE
Recurring perl errors - gmst.pl

### ISSUE THREAD

**Issue by anilkanthi** [Magdoll/SQANTI2#70]
Hi,

I am having the following gmst.pl error:

python sqanti_qc2.py -t 30 --gtf bc1001.gtf gencode.v33.annotation.gtf /gpfs/data/skoklab/home/shared-ali-anil/ref_data/ref/hg38/hg38.fa --fl_count tofu.collapsed.abundance.txt
R scripting front-end version 3.6.1 (2019-07-05)
Write arguments to /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/bc1001.params.txt...
**** Running SQANTI2...
**** Parsing provided files....
Reading genome fasta /gpfs/data/skoklab/home/shared-ali-anil/ref_data/ref/hg38/hg38.fa....
Skipping aligning of sequences because GTF file was provided.

Indels will be not calculated since you ran SQANTI2 without alignment step (SQANTI2 with gtf format as transcriptome input).
**** Predicting ORF sequences...
GeneMarkS: error on last system call, error code 7
Abort program!!!
Traceback (most recent call last):
File "sqanti_qc2.py", line 2198, in 
main()
File "sqanti_qc2.py", line 2191, in main
run(args)
File "sqanti_qc2.py", line 1654, in run
orfDict = correctionPlusORFpred(args, genome_dict)
File "sqanti_qc2.py", line 591, in correctionPlusORFpred
if subprocess.check_call(cmd, shell=True, cwd=gmst_dir)!=0:
File "/gpfs/home/kantha01/.conda/envs/anaCogent3/lib/python3.7/subprocess.py", line 363, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'perl **/gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/utilities/gmst/gmst.pl** -faa --strand direct --fnn --output /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/GMST/GMST_tmp /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/bc1001_corrected.fasta' returned non-zero exit status 1.

After which I ran the failed command and it worked!:
**perl /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/utilities/gmst/gmst.pl -faa --strand direct --fnn --output /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/GMST/GMST_tmp /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/bc1001_corrected.fasta**

But the main command gives the same error. I do require the ORF analysis.
How do I go ahead with this?

**Comment by anilkanthi** [comment]
When I run it with --skipORF, I get a Rscript error:

python sqanti_qc2.py -t 30 --gtf bc1001.gtf gencode.v33.annotation.gtf /gpfs/data/skoklab/home/shared-ali-anil/ref_data/ref/hg38/hg38.fa --fl_count tofu.collapsed.abundance.txt --skipORF
R scripting front-end version 3.6.1 (2019-07-05)
Write arguments to /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/bc1001.params.txt...
**** Running SQANTI2...
**** Parsing provided files....
Reading genome fasta /gpfs/data/skoklab/home/shared-ali-anil/ref_data/ref/hg38/hg38.fa....
Error corrected FASTA /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/bc1001_corrected.fasta already exists. Using it...
**** Predicting ORF sequences...
WARNING: Skipping ORF prediction because user requested it. All isoforms will be non-coding!
WARNING: All input isoforms were predicted as non-coding
**** Parsing Reference Transcriptome....
**** Parsing Isoforms....
Splice Junction Coverage files not provided.
**** Performing Classification of Isoforms....
Number of classified isoforms: 24533
**** RT-switching computation....
**** Reading Full-length read abundance files...
Single-sample PacBio FL count format detected.
Isoforms expression files not provided.
**** Writing output files....
**** Generating SQANTI2 report....
Traceback (most recent call last):
File "sqanti_qc2.py", line 2198, in 
main()
File "sqanti_qc2.py", line 2191, in main
run(args)
File "sqanti_qc2.py", line 1844, in run
if subprocess.check_call(cmd, shell=True)!=0:
File "/gpfs/home/kantha01/.conda/envs/anaCogent3/lib/python3.7/subprocess.py", line 363, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command **'/gpfs/share/apps/R/3.6.1/bin/Rscript** /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/utilities//SQANTI_report2.R /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/bc1001_classification.txt /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/bc1001_junctions.txt /gpfs/data/skoklab/home/kantha01/iso_seq/softwares/SQANTI2/bc1001.params.txt' died with <Signals.SIGKILL: 9>.

**Comment by Magdoll** [comment]
HI @anilkanthi ,
SQANTI2 is getting discontinued and replaced with [SQANTI3](https://github.com/ConesaLab/SQANTI3). I will no longer be supporting SQANTI2 bugs from now on. Could you please test SQANTI3 and if the same error occurs - file in Issues at SQANTI3.

Thanks,
-Liz

**Comment by anilkanthi** [comment]
Hi @Magdoll 
Thank you for that information. I will try this out with SQANTI3.

**Comment by anilkanthi** [comment]
Hi @Magdoll 
I raised this same issue on SQANTI3 8 days ago but I have not received a resolution for the same. It would be great if this is can be expedited somehow.

Thank you.

**Comment by Magdoll** [comment]
I'll look into this issue tomorrow on SQANTI3 and see what I can do.

**Comment by anilkanthi** [comment]
Thank you @Magdoll. Look forward to resolving this issue.

**Comment by Magdoll** [comment]
@anilkanthi I'm closing this becuz we've said we're moving to SQANTI3, right?
