### ISSUE TITLE
Errors in running sqanti2

### ISSUE THREAD

**Issue by JieqiongDai** [Magdoll/SQANTI2#8]
Hi @Magdoll,
I met some problems when running sqanti2, and need your help to figure them out.
First, when running sqanti_qc2.py, I got the below error message:
R scripting front-end version 3.5.2 (2018-12-20)
Cleaning up isoform IDs...
Cleaned up isoform fasta file written to: /data/daij/project/RTEL1_Sharon/CCS/hg38/splicing/sqanti/sqanti2/new/fasta/ccs.NP0328-157_3078_RTEL1_lbc65.lbc65--lbc65.renamed.fasta
[M::mm_idx_gen::123.330*1.73] collected minimizers
[M::mm_idx_gen::149.095*2.55] sorted minimizers
[M::main::149.095*2.55] loaded/built the index for 195 target sequence(s)
[M::mm_mapopt_update::154.771*2.49] mid_occ = 751
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 195
[M::mm_idx_stat::157.585*2.47] distinct minimizers: 167240184 (35.46% are singletons); average occurrences: 6.007; average spacing: 3.086
[M::worker_pipeline::223.786*4.05] mapped 15901 sequences
[M::main] Version: 2.15-r905
[M::main] CMD: minimap2 -ax splice --secondary=no -C5 -uf -t 8 /fdb/igenomes/Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/genome.fa /data/daij/project/RTEL1_Sharon/CCS/hg38/splicing/sqanti/sqanti2/new/fasta/ccs.NP0328-157_3078_RTEL1_lbc65.lbc65--lbc65.renamed.fasta
[M::main] Real time: 224.164 sec; CPU: 906.497 sec; Peak RSS: 18.434 GB
output written to /gpfs/gsfs8/users/daij/project/RTEL1_Sharon/CCS/hg38/splicing/sqanti/sqanti2/new/ccs.NP0328-157_3078_RTEL1_lbc65.lbc65--lbc65.renamed_corrected.fasta
Skipping m54137_181210_213828/5308570/ccs because unmapped.
...
Skipping m54137_181210_213828/56033863/ccs because unmapped.
error in command line
GeneMarkS: error on last system call, error code 256
Abort program!!!
Aligner choice: Minimap2.
**** Running SQANTI...
**** Parsing provided files....
Reading genome fasta /fdb/igenomes/Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/genome.fa....
****Aligning reads with Minimap2...
**** Predicting ORF sequences...
Traceback (most recent call last):
  File "/data/daij/SQANTI2/sqanti_qc2.py", line 1395, in <module>
    main()
  File "/data/daij/SQANTI2/sqanti_qc2.py", line 1391, in main
    run(args)
  File "/data/daij/SQANTI2/sqanti_qc2.py", line 1081, in run
    orfDict = correctionPlusORFpred(args, genome_dict)
  File "/data/daij/SQANTI2/sqanti_qc2.py", line 412, in correctionPlusORFpred
    if subprocess.check_call(cmd, shell=True, cwd=gmst_dir)!=0:
  File "/data/daij/miniconda2/envs/anaCogent5.2/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'perl /gpfs/gsfs8/users/daij/SQANTI2/utilities/gmst/gmst.pl -faa --strand direct --fnn --output /gpfs/gsfs8/users/daij/project/RTEL1_Sharon/CCS/hg38/splicing/sqanti/sqanti2/new/GMST/GMST_tmp /gpfs/gsfs8/users/daij/project/RTEL1_Sharon/CCS/hg38/splicing/sqanti/sqanti2/new/ccs.NP0328-157_3078_RTEL1_lbc65.lbc65--lbc65.renamed_corrected.fasta' returned non-zero exit status 1

Second, when running sqanti_filter2.py, I got another error message:

Running SQANTI filtering...

Traceback (most recent call last):
  File "/data/daij/SQANTI2/sqanti_filter2.py", line 119, in <module>
    main()
  File "/data/daij/SQANTI2/sqanti_filter2.py", line 114, in main
    sqanti_filter_lite(args)
  File "/data/daij/SQANTI2/sqanti_filter2.py", line 55, in sqanti_filter_lite
    cat = CATEGORY_DICT[r['structural_category']]
KeyError: 'fusion'

Do you have any idea about that?

Thanks a lot,

Jieqiong

**Comment by Magdoll** [comment]
Hi @JieqiongDai ,

This is the gene prediction program GMST failing. There are few possibilities:

1. Can you check that the file `
/gpfs/gsfs8/users/daij/project/RTEL1_Sharon/CCS/hg38/splicing/sqanti/sqanti2/new/ccs.NP0328-157_3078_RTEL1_lbc65.lbc65--lbc65.renamed_corrected.fasta` is not empty?

2. Before you re-run SQANTI2 in the same directory, please clean up the GMST directory first.

````
rm -rf GMST
```

If after trying both steps above you still fail, please directly run the failed command:

```
perl /gpfs/gsfs8/users/daij/SQANTI2/utilities/gmst/gmst.pl -faa --strand direct --fnn --output /gpfs/gsfs8/users/daij/project/RTEL1_Sharon/CCS/hg38/splicing/sqanti/sqanti2/new/GMST/GMST_tmp /gpfs/gsfs8/users/daij/project/RTEL1_Sharon/CCS/hg38/splicing/sqanti/sqanti2/new/ccs.NP0328-157_3078_RTEL1_lbc65.lbc65--lbc65.renamed_corrected.fasta
```

and let me know what errors show up.

**Comment by JieqiongDai** [comment]
Hi @Magdoll,
Thanks for your help. 
Unfortunately I tried all the solutions you mentioned, but still get the same error message.
I was able to run sqanti with the same data, so I assume my data has no problem.
Do you have any idea about that?


Best,
Jieqiong

**Comment by Magdoll** [comment]
Hi,

Sorry I just realized you posted two errors. Looks like error 1 is fixed.

I just fixed error 2 for this error below. Plz update and try again.

```
Traceback (most recent call last):
File "/data/daij/SQANTI2/sqanti_filter2.py", line 119, in 
main()
File "/data/daij/SQANTI2/sqanti_filter2.py", line 114, in main
sqanti_filter_lite(args)
File "/data/daij/SQANTI2/sqanti_filter2.py", line 55, in sqanti_filter_lite
cat = CATEGORY_DICT[r['structural_category']]
KeyError: 'fusion'
```

**Comment by madhurimab2705** [comment]
Hello,
I face a similar issue when trying to run SQANTI2. This is the error log:

_python sqanti2/SQANTI2/sqanti_qc2.py -t 30 m54111_190817_082114_.fl.dT_BC1003_PB_3p--primer_5p.polished_collapsed.collapsed.rep.fq reference/gencode.vM23.annotation.gtf reference/GRCm38.p6.genome.fa
R scripting front-end version 3.6.1 (2019-07-05)
Cleaning up isoform IDs...
Cleaned up isoform fasta file written to: /scratch/madhurima/pacbio/m54111_190817_082114_.fl.dT_BC1003_PB_3p--primer_5p.polished_collapsed.collapsed.rep.renamed.fasta
**** Running SQANTI...
**** Parsing provided files....
Reading genome fasta /scratch/madhurima/pacbio/reference/GRCm38.p6.genome.fa....
****Aligning reads with Minimap2...
[M::mm_idx_gen::88.384*1.52] collected minimizers
[M::mm_idx_gen::159.386*1.54] sorted minimizers
[M::main::159.386*1.54] loaded/built the index for 139 target sequence(s)
[M::mm_mapopt_update::162.794*1.53] mid_occ = 656
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 139
[M::mm_idx_stat::164.818*1.52] distinct minimizers: 163933854 (36.16% are singletons); average occurrences: 5.586; average spacing: 3.009
[M::worker_pipeline::165.123*1.52] mapped 214 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -ax splice --secondary=no -C5 -uf -t 30 /scratch/madhurima/pacbio/reference/GRCm38.p6.genome.fa /scratch/madhurima/pacbio/m54111_190817_082114_.fl.dT_BC1003_PB_3p--primer_5p.polished_collapsed.collapsed.rep.renamed.fasta
[M::main] Real time: 165.240 sec; CPU: 251.035 sec; Peak RSS: 17.166 GB
output written to
**** Predicting ORF sequences...
error in command line
GeneMarkS: error on last system call, error code 256
Abort program!!!
Traceback (most recent call last):
  File "sqanti2/SQANTI2/sqanti_qc2.py", line 1800, in <module>
    main()
  File "sqanti2/SQANTI2/sqanti_qc2.py", line 1796, in main
    run(args)
  File "sqanti2/SQANTI2/sqanti_qc2.py", line 1418, in run
    orfDict = correctionPlusORFpred(args, genome_dict)
  File "sqanti2/SQANTI2/sqanti_qc2.py", line 556, in correctionPlusORFpred
    if subprocess.check_call(cmd, shell=True, cwd=gmst_dir)!=0:
  File "/home/madhurima/.conda/envs/anaCogent3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)_

I tried to separately run the command: 

_perl /scratch/madhurima/pacbio/sqanti2/SQANTI2/utilities/gmst/gmst.pl -faa --strand direct --fnn --output /scratch/madhurima/pacbio/GMST/GMST_tmp /scratch/madhurima/pacbio/m54111_190817_082114_.fl.dT_BC1003_PB_3p--primer_5p.polished_collapsed.collapsed.rep.renamed_corrected.fasta
error in command line
GeneMarkS: error on last system call, error code 256
Abort program!!!_

I have tried deleting the GMST folder and my FASTQ file is not empty. Could you please help me resolve this issue.

Thanks a lot,
Madhurima
