### ISSUE TITLE
args.aligner_choice error when running with -g option

### ISSUE THREAD

**Issue by hvbakel** [Magdoll/SQANTI2#9]
When running squanti2 with the -g option (i.e. providing a gtf rather than an input fasta file), the program fails with a namespace error.

**Comment by hvbakel** [comment]
After initializing args.aligner_choice to an empty string, sqanti_qc2.py will keep running, but it breaks again after cleaning the isoform IDs (which it should not do for a provided gtf file). It looks like the --gtf parameter is broken altogether.

**Comment by Magdoll** [comment]
Hi @hvbakel ,

You are right `args.gtf` is not implemented. I'll look into whether I should support it (it was supported in the original SQANTI) or I should remove the parameter. Thank you for notifying.

--Liz

**Comment by Magdoll** [comment]
I decided that for the moment I will not be supporting `--gtf`.

**Comment by hvbakel** [comment]
Ok understood. Will try to make our isoseq pipeline work with the isoform fasta instead.

Just a quick note, since yesterday's commit, the squanti2 pipeline is failing on "from BED import LazyBEDPointReader". I'm guessing it's a new function not yet committed in the cDNA_cupcake repo?

**Comment by Magdoll** [comment]
Thank you for pointing out the BED.py dependency failure. I have just updated the cDNA_Cupcake repo.
